Proxy
-
- proxy is to handle things differently.  
- `proxy = new Proxy(target, handler)` to make proxy.  
- proxy can be prototype.  
- `target.a` would return the `a` prop of `target`, and so would `proxy.a` if handler has no limit (eg. handler is empty object), but if not then it would return what is in the handler.  
- intercept methods of proxy:  
  - `get(target, prop, receiver)` intercept all gets (eg. `proxy.a`) 
  - `set(target, prop, value, reveiver)`, all sets, returns bool  
  - `has(target, prop)`, all `propKey in proxy`  
  - `deleteProperty(target, prop)`, all `delete proxy[prop]`, returns bool  
  - `ownKeys(target)` all methods that get all props (iterators).  
  - `getOwnPropertyDescriptors(target, prop)`  
  - `defineProperty(target, prop, propDesc)`  
  - `preventExtensions(target)` 
  - `getPrototypeOf(target)`  
  - `isExtensible(target)`  
  - `setPrototypeOf(target)`  
  - `apply(target, obj, args)`, all of `proxy(...args)`, `proxy.call(obj, ...args)`, `proxy.apply(...)`.  
  - `construct(target, args)`  
- proxy has many problem with `this`, use `Reflect` for methods with `this`.    
  
Reflect
-
- gets the private methods of an obj (with the correct `this`) and changes the return value of some.  
- has all the methods of proxy with same names and params.  
- adding the receiver param to reflect method in a proxy may cause problems.  

Promise
- 
- promise objects are for async.  
- `Promise` obj can have 3 states:`pending`, `fulfilled`, `rejected` and will not change after the first change (pending->fulfilled, or pending->rejected).  
- `promise = new Promise(fun(resolve, reject) {})` to make new promise, has a function as param and this function has `resolve` and `reject` function as params. Then use `resolve(value)` to make it resolved and `reject(value)` to make it rejected.  
- to use the value of `resolved` and `rejected` with a function:  
````javascript
promise.then(function(value) {
  // success
}, function(error) {
  // failure
});
````
- `catch()`method is just like `then()`, but only for errors.  
- once promise is resolved, no errors can be thrown.  
- you can then after then, like `promise.then().catch().then()`, note that the catch will not catch the errors in the last then.  
- `finally()` would be called regardless of the state of promise.  
-  `Promise.all([])` makes multiple promises into one: 
    - it is fulfilled only when all promises are fulfilled and the results of all the promises will be returned in an array.  
    - it is rejected when either promise is rejected and the value rejected will be returned, but if the rejection is caught then the within then it won't be caught by `all` as a rejection.  
- `Promise.race([])`, takes multiple promises and the state would change with the first promise to change. Returns the value returned by the promise.  
- `Promise.resolve(obj)`: 
  - if thenable object, create promise and call then method.  
  - if not then make a resolved dummy promise and add the obj to it.  
  - if no param, return new resolved promise.  
- `Promise.reject(obj)`: just like `Promise.resolve` but by default it returns a rejected promise.  
- `Promise.try(f)`, param f is the promise. Acts still as the same promise. Used when the `catch` needs to catch async and sync errors.  

Iterator and for...of
-
- iterator object uses `next()` method to call one by one. mostly to serve `for...of`
- `for...of` loop looks for the iterator.  
- example of making iterable object:  
````javascript
const obj = {
  [Symbol.iterator] : function () {
    return {
      next: function () {
        return {
          value: 1,
          done: true
        };
      }
    };
  }
};
````
- iterator also serves `...`
- having an iterable obj after `yield*` will make the obj elements also called one by one.  
- iterator can also have `return()` and `throw()` methods.  
- objs like arrays, when changed to array with `Array.from`, can be added with an iterator.  
- `for(let key of Object.keys(obj)) {}` could be used to go through an object without an iterator and then you can also make a generator with this.  

generator  
-
- generators have `*` between `function` and function name.  
- use `yield`  
- generators are pointed when called, not calculated. They are calculated up till the next `yield` when `gen.next()` is called.  
- `yield` statements have to be in `()` when used in other statements. eg. `console.log((yield))`
- generators can be used to make iterators for objects.  
- param of `next()` is a var that can be used as the value of the last yield. (this won't work for the first `next` as there is no 'last')
- once the `done` prop of the generator is true, the `for...of` loop will stop and nothing will be returned.  
- `throw()` method to throw errors outside of generator.  
- once you used `next`, errors thrown by the `throw()` method can be caught by `catch` inside the generator.  
- if generator throws an error inside and is not caught, it returns `undefined` and `done` becomes true.  
- use `*` after `yield` if you want to yield another generator, this is the same with iterators.  
- add `*` before function to make it a generator method. eg. `*GenMeth() {}`, or after `function`, eg. `genMeth = function* () {}`
- the children of a generator prototype would inherit the methods of the prototype object because it has no `this`.  
- `var f = GenFun.call(F.prototype);` could be used to make the generator able to use `this` normally (eg. GenFun.prop) while still works with `next()`.  
- can't understand:  
`协程（coroutine）是一种程序运行的方式，可以理解成“协作的线程”或“协作的函数”。协程既可以用单线程实现，也可以用多线程实现。前者是一种特殊的子例程，后者是一种特殊的线程。
**（1）协程与子例程的差异**
传统的“子例程”（subroutine）采用堆栈式“后进先出”的执行方式，只有当调用的子函数完全执行完毕，才会结束执行父函数。协程与其不同，多个线程（单线程情况下，即多个函数）可以并行执行，但是只有一个线程（或函数）处于正在运行的状态，其他线程（或函数）都处于暂停态（suspended），线程（或函数）之间可以交换执行权。也就是说，一个线程（或函数）执行到一半，可以暂停执行，将执行权交给另一个线程（或函数），等到稍后收回执行权的时候，再恢复执行。这种可以并行执行、交换执行权的线程（或函数），就称为协程。
从实现上看，在内存中，子例程只使用一个栈（stack），而协程是同时存在多个栈，但只有一个栈是在运行状态，也就是说，协程是以多占用内存为代价，实现多任务的并行。
**（2）协程与普通线程的差异**
不难看出，协程适合用于多任务运行的环境。在这个意义上，它与普通的线程很相似，都有自己的执行上下文、可以分享全局变量。它们的不同之处在于，同一时间可以有多个线程处于运行状态，但是运行的协程只能有一个，其他协程都处于暂停状态。此外，普通的线程是抢先式的，到底哪个线程优先得到资源，必须由运行环境决定，但是协程是合作式的，执行权由协程自己分配。
由于 JavaScript 是单线程语言，只能保持一个调用栈。引入协程以后，每个任务可以保持自己的调用栈。这样做的最大好处，就是抛出错误的时候，可以找到原始的调用栈。不至于像异步操作的回调函数那样，一旦出错，原始的调用栈早就结束。
Generator 函数是 ES6 对协程的实现，但属于不完全实现。Generator 函数被称为“半协程”（semi-coroutine），意思是只有 Generator 函数的调用者，才能将程序的执行权还给 Generator 函数。如果是完全执行的协程，任何函数都可以让暂停的协程继续执行。
如果将 Generator 函数当作协程，完全可以将多个需要互相协作的任务写成 Generator 函数，它们之间使用`yield`表达式交换控制权。`

- can use async in `yield` statements. eg.
````javascript
function* loadUI() {
  showLoadingScreen();
  yield loadUIDataAsynchronously();
  hideLoadingScreen();
}
````
- 
